
#####################################################################

spring:
  application:
    name: ${app.id}
  ## default profile
  profiles:
    active: win
  ## Jackson config
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  ## i18n message
  messages:
    basename: msg/messages,msg/errors
    encoding: UTF-8

#####################################################################

glacispring:
  common:
    servlet-context-listener-enabled: true
#  httpclient:
#    enabled: true
#    apollo-support: true
#  httpclients:
#    default:
#      hosts: http://127.0.0.1:8080,http://127.0.0.1:8081
#      verbose-log: true

#####################################################################

# Other configs
debug: false
